INSERT INTO smn_compras.smn_documentos
(
	smn_documentos_id,
	smn_tipo_documento_id,
	dcc_codigo,
	dcc_nombre,
	dcc_transaccion_id,
	dcc_recurrente,
	dcc_fecha_inicio,
	dcc_fecha_final,
	dcc_modalidad,
	dcc_esoferta,
	dcc_cant_ofertas,
	dcc_moneda_alterna,
	dcc_idioma,
	dcc_usuario_id,
	dcc_fecha_registro,
	dcc_hora,
	dcc_genera_pedido,
	dcc_cant_dias_cierre,
	dcc_hora_cierre
)
VALUES
(
	${seq:currval@smn_compras.seq_smn_documentos},
	${fld:smn_tipo_documento_id},
	${fld:dcc_codigo},
	${fld:dcc_nombre},
	${fld:dcc_transaccion_id},
	${fld:dcc_recurrente},
	${fld:dcc_fecha_inicio},
	${fld:dcc_fecha_final},
	${fld:dcc_modalidad},
	${fld:dcc_esoferta},
	${fld:dcc_cant_ofertas},
	${fld:dcc_moneda_alterna},
	'${def:locale}',
	'${def:user}',
	'${def:date}',
	'${def:time}',
	${fld:dcc_genera_pedido},
	${fld:dcc_cant_dias_cierre},
	${fld:dcc_hora_cierre}
)
