select
		smn_compras.smn_tipo_documento.tid_codigo,
	smn_compras.smn_tipo_documento.tid_nombre,
	smn_compras.smn_tipo_documento.tid_empresa,
	smn_compras.smn_tipo_documento.tid_sucursal,
	smn_compras.smn_tipo_documento.tid_area_servicio,
	smn_compras.smn_tipo_documento.tid_unidad_servicio,
	smn_compras.smn_tipo_documento.tid_req_control_fiscal,
	smn_compras.smn_tipo_documento.tid_serie,
	smn_compras.smn_tipo_documento.tid_numero_fiscal,
	smn_compras.smn_tipo_documento.tid_requiere_control_interno,
	smn_compras.smn_tipo_documento.tid_numero_control,
	smn_compras.smn_tipo_documento.tid_fecha_registro,
	smn_compras.smn_tipo_documento.tdc_codigo,
	smn_compras.smn_tipo_documento.tdc_nombre,
	smn_compras.smn_tipo_documento.tdc_naturaleza,
	smn_compras.smn_tipo_documento.tdc_fecha_registro
from
	smn_compras.smn_tipo_documento 
where
	smn_compras.smn_tipo_documento.smn_tipo_documento_id = ${fld:id}
