select
	smn_compras.smn_requisicion_cabecera.smn_cabecera_version_id,
	smn_compras.smn_requisicion_cabecera.req_numero,
	smn_compras.smn_requisicion_cabecera.req_estatus,
	smn_compras.smn_requisicion_cabecera.smn_tipo_documento_id,
	smn_compras.smn_requisicion_cabecera.smn_documento_id,
	smn_compras.smn_requisicion_cabecera.req_descripcion,
	smn_compras.smn_requisicion_cabecera.req_fecha_requerido,
	smn_compras.smn_requisicion_cabecera.req_estatus_ruta,
	smn_compras.smn_requisicion_cabecera.smn_entidad_id,
	smn_compras.smn_requisicion_cabecera.smn_sucursal_id,
	smn_compras.smn_requisicion_cabecera.req_fecha_registro
from
	smn_compras.smn_requisicion_cabecera 
where
	smn_compras.smn_requisicion_cabecera.smn_requisicion_cabecera_id = ${fld:id}
