INSERT INTO smn_compras.smn_roles
(
	smn_roles_id,
	smn_usuarios_id,
	rol_tipo,
	smn_corporaciones_id,
	smn_entidades_id,
	smn_sucursales_id,
	smn_areas_servicios_id,
	smn_unidades_servicios_id,
	smn_estructura_organizacional_id,
	rol_idioma,
	rol_usuario_id,
	rol_fecha_registro,
	rol_hora
)
VALUES
(
	${seq:currval@smn_compras.seq_smn_roles},
	${fld:smn_usuarios_id},
	${fld:rol_tipo},
	${fld:smn_corporaciones_id},
	${fld:smn_entidades_id},
	${fld:smn_sucursales_id},
	${fld:smn_areas_servicios_id},
	${fld:smn_unidades_servicios_id},
	${fld:smn_estructura_organizacional_id},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
