select
		smn_compras.smn_orden_compra_impuesto.smn_orden_compra_impuesto_id,
select
		smn_compras.smn_orden_compra_impuesto.smn_orden_compra_impuesto_id,
select
		smn_compras.smn_orden_compra_impuesto.smn_orden_compra_impuesto_id,
	smn_compras.smn_orden_compra_impuesto.smn_cod_impuesto_deduc_rf,
	smn_compras.smn_orden_compra_impuesto.oci_monto_base_ml,
	smn_compras.smn_orden_compra_impuesto.oci_porcentaje_impuesto,
	smn_compras.smn_orden_compra_impuesto.oci_sustraendo_ml,
	smn_compras.smn_orden_compra_impuesto.smn_tipo_impuesto_rf,
	smn_compras.smn_orden_compra_impuesto.oci_monto_impuesto_ml,
	smn_compras.smn_orden_compra_impuesto.fecha_registro
	
from
	smn_compras.smn_orden_compra_impuesto
