select
		smn_compras.smn_orden_compra_descuentos_retenciones.smn_orden_compra_descuentos_retenciones_id,
select
		smn_compras.smn_orden_compra_descuentos_retenciones.smn_orden_compra_descuentos_retenciones_id,
select
		smn_compras.smn_orden_compra_descuentos_retenciones.smn_orden_compra_descuentos_retenciones_id,
	smn_compras.smn_orden_compra_descuentos_retenciones.smn_codigo_descuento_rf,
	smn_compras.smn_orden_compra_descuentos_retenciones.ocd_monto_base,
	smn_compras.smn_orden_compra_descuentos_retenciones.ocd_porcentaje,
	smn_compras.smn_orden_compra_descuentos_retenciones.ocd_monto_descuento,
	smn_compras.smn_orden_compra_descuentos_retenciones.smn_moneda_rf,
	smn_compras.smn_orden_compra_descuentos_retenciones.fecha_registro
	
from
	smn_compras.smn_orden_compra_descuentos_retenciones
