select
		smn_compras.smn_requisicion_detalle.smn_requisicion_detalle_id,
	smn_compras.smn_requisicion_cabecera.smn_requisicion_cabecera_id,
	smn_compras.smn_requisicion_cabecera.req_estatus as req_estatus_pl0,
	smn_compras.smn_requisicion_detalle.smn_linea_id,
	smn_compras.smn_requisicion_detalle.smn_contrato_id,
	smn_compras.smn_requisicion_detalle.rss_cantidad,
	smn_compras.smn_requisicion_detalle.rrs_precio,
	smn_compras.smn_requisicion_detalle.rrs_monto,
	smn_compras.smn_requisicion_detalle.rrs_fecha_registro
	
from
	smn_compras.smn_requisicion_cabecera,
	smn_compras.smn_requisicion_detalle
where
	smn_compras.smn_requisicion_cabecera.smn_requisicion_cabecera_id=smn_compras.smn_requisicion_detalle.smn_requisicion_cabecera_id
